name: ci
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e ".[dev,a2a,mcp]"
      - name: Lint
        run: make lint
      - name: Test (emit evidence)
        run: |
          # Determine milestone from branch name or use M3 as default for M3 features
          MILESTONE=$(echo ${{ github.ref_name }} | grep -oE 'M[0-9]+' || echo "M3")
          # Enable A2A and MCP features for CI testing
          export APEX_A2A_INGRESS=1
          export APEX_MCP_SERVER=1
          ARTIFACTS_DIR=docs/${MILESTONE}/artifacts make test
      - name: Upload artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evidence-artifacts
          path: docs/*/artifacts/**
          if-no-files-found: ignore